name: Lineages Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
  schedule:
    # schedule the script to run M-F at 7:30am
    # see this for details https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
    - cron: "30 7 * * 1-5"
jobs:
  Run-Lineages-Pipeline:
    runs-on: ubuntu-latest
        
    steps:
       - name: Check out repository code
         uses: actions/checkout@v3
       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
       
       - name: Setup dependencies
         uses: actions/checkout@v3
       - name: Setup R
         uses: r-lib/actions/setup-r@v2
       - name: Setup Renv
         uses: r-lib/actions/setup-renv@v2
         # uses: r-lib/actions/setup-r-dependencies@v2
         # with:
         #   cache-version: 2
        
         
       # Run R script
       - name: Run the lineages script
         run: Rscript scripts/lineages_public_repo.R
#          with:
#            cache-version: 1
#            extra-packages: |
#              lorenzwalthert/touchstone
#              ggplot2
#              dplyr

           
       # Add new files in data folder, commit along with other modified files, push
       - name: Commit files
         run: |
           git config --local user.name actions-user
           git config --local user.email "actions@github.com"
           git fetch
           git add .
           git commit -am "GH ACTION Headlines $(date)"
           git push origin main
         env:
           repo_token: ${{secrets.GITHUB_TOKEN}}
           username: github-actions
